#! /bin/bash

eleccion=$(printf "Lock \nPoweroff \nReboot \nSuspend 󰤄\nLogout 󰈆" | dmenu -i )

case "$eleccion" in
	"Lock ") slock ;;
	"Poweroff ") systemctl poweroff ;;
	"Reboot ") systemctl reboot ;;
	"Suspend 󰤄") systemctl suspend ;;
	"Logout 󰈆")  kill -9 -1 ;;
	*) exit 1 ;;
esac
